version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8000:80"
    depends_on:
      - web
    volumes:
      - .:/var/labhacker/wikilegis
      - ./config/nginx:/etc/nginx/conf.d
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python config.py && ./start.sh"
    volumes:
      - .:/var/labhacker/wikilegis
    environment:
      - ADMIN_PASSWORD=123
      - ADMIN_EMAIL=admin@admin.com
      - DATABASE_ENGINE=postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=False
    expose:
      - "8000"
    depends_on:
      - db
