version: '2'
services:
  db:
    image: postgres      
  nginx:
    image: nginx
    depends_on:
      - web
    volumes_from:
      - web
    volumes:
      - ./config/etc/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
  web:
    build: .
    command: ./start.sh
    links:
      - db
    volumes:
      - data:/var/labhacker/wikilegis
    environment:
      - ADMIN_PASSWORD=123
      - ADMIN_EMAIL=admin@admin.com
      - DATABASE_ENGINE=postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DEBUG=False
    expose:
      - "8000"
    depends_on:
      - db

volumes:
  data:
    driver: local